all: haleakala_shakespeare_voyage_msr.pdf

SRC = ../..
include $(SRC)/common.mk

haleakala_shakespeare_voyage_msr.pdf: \
    $(SRC)/original/marches/4-4/road_to_haleakala.ly \
    $(SRC)/original/dances/strathspeys/shakespeare_garden.ly \
    $(SRC)/original/dances/reels/great_voyage.ly
